# Generated by Django 3.0.3 on 2020-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('tag', models.CharField(max_length=300)),
                ('presenter', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('full_information', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
