# Generated by Django 3.0.7 on 2020-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date_received', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default='Present')),
                ('achievement1', models.TextField()),
                ('achievement2', models.TextField()),
                ('achievement3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('technologies', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('achievement1', models.TextField()),
                ('achievement2', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default='Present')),
            ],
        ),
    ]
