# Generated by Django 3.0.7 on 2020-09-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
