# Generated by Django 3.0.5 on 2020-04-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_job_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
