# Generated by Django 3.0.7 on 2020-09-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20200903_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
