# Generated by Django 3.0.7 on 2020-09-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_auto_20200903_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
