# Generated by Django 3.0.7 on 2020-09-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20200903_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
