# Generated by Django 3.0.7 on 2020-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_auto_20200903_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
